owner: wtznc # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Tyziniec.com
    url: $SERVICE_2
  - name: Pi-hole
    url: $SERVICE_1
  - name: Uptime
    url: $SERVICE_3

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: dash.tyziniec.com
  # baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from GitHub repository. Relies on GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
